/* SPDX-License-Identifier: GPL-2.0-only */
/* Copyright (C) 2023 Intel Corporation */

#ifndef IPU4_PLATFORM_BUTTRESS_REGS_H
#define IPU4_PLATFORM_BUTTRESS_REGS_H

#include <linux/bits.h>

// From 4.19 ambu kernel (IPU4_ prefix added)
#define IPU4_IS_FREQ_CTL_DIVISOR 0x4
#define IPU4_BUTTRESS_PWR_STATE_IS_PWR_FSM_SHIFT	20
#define IPU4_BUTTRESS_PWR_STATE_IS_PWR_FSM_MASK	(0xf << 20)
#define IPU4_BUTTRESS_PWR_STATE_IS_PWR_FSM_IDLE	0x0
#define IPU4_BUTTRESS_PWR_STATE_IS_PWR_FSM_IS_RDY	0xa
#define IPU4_PS_FREQ_CTL_DEFAULT_RATIO	0x12
#define IPU4_BUTTRESS_PWR_STATE_PS_PWR_FSM_SHIFT	24
#define IPU4_BUTTRESS_PWR_STATE_PS_PWR_FSM_MASK	(0x1f << 24)
#define IPU4_BUTTRESS_PWR_STATE_PS_PWR_FSM_IDLE	0x0
#define IPU4_BUTTRESS_PWR_STATE_PS_PWR_FSM_PS_PWR_UP	0xf

/* Ice Lake IPU4P uses a wider power FSM field and different ready states. */
#define IPU4P_BUTTRESS_PWR_STATE_IS_PWR_FSM_SHIFT	20
#define IPU4P_BUTTRESS_PWR_STATE_IS_PWR_FSM_MASK	(0x1f << 20)
#define IPU4P_BUTTRESS_PWR_STATE_IS_PWR_FSM_IDLE	0x0
#define IPU4P_BUTTRESS_PWR_STATE_IS_PWR_FSM_IS_RDY	0xc
#define IPU4P_BUTTRESS_PWR_STATE_PS_PWR_FSM_SHIFT	25
#define IPU4P_BUTTRESS_PWR_STATE_PS_PWR_FSM_MASK	(0x1f << 25)
#define IPU4P_BUTTRESS_PWR_STATE_PS_PWR_FSM_IDLE	0x0
#define IPU4P_BUTTRESS_PWR_STATE_PS_PWR_FSM_PS_PWR_UP	0x10

#define IPU4P_BUTTRESS_REG_IS_FREQ_CTL_RATIO_SHIFT	1
#define IPU4P_BUTTRESS_REG_PS_FREQ_CTL_RATIO_SHIFT	8
#define IPU4P_BUTTRESS_REG_PS_FREQ_CTL_OVRD_SHIFT	7

#define IPU4_BUTTRESS_FREQ_CTL_ICCMAX_LEVEL		0
#define IPU4_BUTTRESS_PWR_STATE_HH_STATUS_MASK		GENMASK(13, 12)


#endif // IPU4_PLATFORM_BUTTRESS_REGS_H
